from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent

RAW_DATA_DIR = PROJECT_ROOT / "data" / "raw"
PROCESSED_DATA_DIR = PROJECT_ROOT / "data" / "processed"
EXTERNAL_DATA_DIR = PROJECT_ROOT / "data" / "external"

RESULTS_DIR = PROJECT_ROOT / "results"
FIGURES_DIR = PROJECT_ROOT / "figures"
MODEL_DIR = PROJECT_ROOT / "models"

RANDOM_STATE = 42

PROTVEC_DIM = 100
NODE2VEC_DIM = 100

TEST_SIZE = 0.2
BATCH_SIZE = 32
EPOCHS = 100
VALIDATION_SPLIT = 0.2
DROPOUT_RATE = 0.2
LEARNING_RATE = 0.001

N_SPLITS = 5
NEGATIVE_RATIO = 10
SIMILARITY_THRESHOLD = 0.3
